# Generated by Django 4.1.1 on 2022-09-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0001_initial'),
        ('cars', '0002_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealershp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dealerships.dealership'),
            preserve_default=False,
        ),
    ]
